FROM ubuntu:17.10 
MAINTAINER dcarrascal75@gmail.com 

RUN apt-get update && \
    apt-get install -y openssh-server pwgen netcat net-tools curl wget && \
    apt-get clean all

# python and relevant tools 
RUN apt-get update && apt-get install -y \ 
        build-essential \ 
	python \ 
	python-dev \ 
	libxml2-dev \ 
	libxslt-dev \ 
	libssl-dev \ 
	zlib1g-dev \ 
	libyaml-dev \ 
	libffi-dev \ 
	python-pip

# Latest versions of python tools via pip 
RUN pip install --upgrade pip \ 
	virtualenv \ 
	requests

RUN ln -sf /usr/share/zoneinfo/Europe/Madrid /etc/localtime
RUN mkdir /var/run/sshd

RUN sed -ri 's/^PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config

RUN mkdir /root/.ssh
COPY id_rsa.pub /root/.ssh/authorized_keys
RUN chmod 400 /root/.ssh/authorized_keys

EXPOSE 22 
CMD ["/usr/sbin/sshd", "-D"]


